namespace Streamx.Linq.SQL.PostgreSQL {
    public enum DatePart {
        EPOCH,
        CENTURY,
        DECADE,
        MILLENNIUM,
        YEAR,
        ISOYEAR,
        QUARTER,
        MONTH,
        WEEK,
        DAY,
        DOW,
        DOY,
        ISODOW,
        HOUR,
        MINUTE,
        SECOND,
        MILLISECONDS,
        MICROSECONDS,
        TIMEZONE,
        TIMEZONE_HOUR,
        TIMEZONE_MINUTE,
    }
}
